// Self-service View icon sets (Notion-style icon picker for view tabs,
// 2026-09-03). Sandra: "when renaming views can we now push for icon
// sets? follow the same format as in the project categories. allow to
// change colors too. We have an existing view color picker." -- this
// mirrors categoryIcons.ts's shape (a flat name->component library plus a
// fixed list the picker renders from), but far larger and organized into
// named sections with a search box on top (see ViewTabs.tsx's icon
// picker), matching the "Search icons..." + grouped-sections structure
// she specified rather than category.ts's single flat grid (which only
// ever needed ~24 icons).
//
// A view's own icon is optional (TableView.icon) -- unset means "use the
// default icon for this view's type" (VIEW_TYPE_ICONS in ViewTabs.tsx,
// unchanged), so every already-saved view keeps rendering exactly as it
// did before this existed. Once a name here is chosen it's stored as
// plain text on the view record; if that name is ever removed from this
// library (shouldn't normally happen) the tab just falls back to the
// view-type default the same way an unset icon does.
import {
  Briefcase, Building2, Handshake, Landmark, Target, Presentation,
  Folder, FileText, ClipboardList, Calendar, Mail, Globe,
  Search, Settings, Star, LayoutDashboard, List, ListChecks,
  Table, Grid3X3, Kanban, FolderKanban, ClipboardCheck, Workflow,
  GitBranch, Layers, Milestone, Flag, Tag, Inbox,
  ChartBar, ChartColumn, ChartLine, ChartPie, ChartSpline, TrendingUp,
  TrendingDown, Activity, Gauge, CircleGauge, Percent, Database,
  Table2, ArrowUpDown, Scale, Clock, Timer, Hourglass,
  CalendarDays, CalendarRange, CalendarClock, CalendarCheck, CalendarPlus, AlarmClock,
  History, RefreshCw, Play, Pause, TimerReset, User,
  Users, UserRound, UsersRound, UserCheck, UserPlus, UserMinus,
  UserCog, UserSearch, Contact, IdCard, CircleUserRound, MessagesSquare,
  AtSign, CircleCheck, CheckCheck, CircleAlert, TriangleAlert, CircleX,
  Info, Flame, Zap, Sparkles, Eye, Bell,
  CircleDashed, Monitor, Laptop, Smartphone, Server, HardDrive,
  Cpu, Cloud, Wifi, Network, Cable, CodeXml,
  Terminal, Bug, Wrench, Shield, ShieldCheck, ShieldAlert,
  ShieldX, Lock, LockOpen, KeyRound, Fingerprint, ScanFace,
  EyeOff, FileLock, DatabaseBackup, Siren, Pizza, Sandwich,
  Croissant, Cookie, CakeSlice, IceCreamCone, Apple, Cherry,
  Citrus, Grape, Coffee, CupSoda, Utensils, Soup,
  ChefHat, Dog, Cat, Rabbit, Squirrel, Bird,
  Fish, Turtle, Snail, Worm, Rat, PawPrint,
  Shell, FishSymbol, Feather, Smile, Laugh, Frown,
  Meh, Annoyed, Angry, SmilePlus, ThumbsUp, ThumbsDown,
  Heart, Glasses, PartyPopper, Leaf, Flower, Flower2,
  Sprout, TreePine, Trees, TreeDeciduous, Mountain, Sun,
  Moon, Rainbow, Snowflake, Waves, Wind, Plane,
  PlaneTakeoff, Car, Bus, Train, Ship, Map,
  MapPin, Navigation, Compass, Route, Hotel, House,
  Luggage, Earth, MailOpen, Send, MessageSquare, MessageCircle,
  Phone, PhoneCall, Video, Megaphone, Share2, Paperclip,
  File, FileSpreadsheet, FileCheck, FileClock, FileSearch, Files,
  FolderOpen, Notebook, Book, BookOpen, Library, Clipboard,
  Archive, Lightbulb, Brain, Rocket, Telescope, Microscope,
  FlaskConical, Atom, Puzzle, Shapes, Circle, Triangle,
  Square, Diamond, Infinity,
  type LucideIcon,
} from "lucide-react";

export const VIEW_ICON_LIBRARY: Record<string, LucideIcon> = {
  Briefcase,
  Building2,
  Handshake,
  Landmark,
  Target,
  Presentation,
  Folder,
  FileText,
  ClipboardList,
  Calendar,
  Mail,
  Globe,
  Search,
  Settings,
  Star,
  LayoutDashboard,
  List,
  ListChecks,
  Table,
  Grid3X3,
  Kanban,
  FolderKanban,
  ClipboardCheck,
  Workflow,
  GitBranch,
  Layers,
  Milestone,
  Flag,
  Tag,
  Inbox,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartSpline,
  TrendingUp,
  TrendingDown,
  Activity,
  Gauge,
  CircleGauge,
  Percent,
  Database,
  Table2,
  ArrowUpDown,
  Scale,
  Clock,
  Timer,
  Hourglass,
  CalendarDays,
  CalendarRange,
  CalendarClock,
  CalendarCheck,
  CalendarPlus,
  AlarmClock,
  History,
  RefreshCw,
  Play,
  Pause,
  TimerReset,
  User,
  Users,
  UserRound,
  UsersRound,
  UserCheck,
  UserPlus,
  UserMinus,
  UserCog,
  UserSearch,
  Contact,
  IdCard,
  CircleUserRound,
  MessagesSquare,
  AtSign,
  CircleCheck,
  CheckCheck,
  CircleAlert,
  TriangleAlert,
  CircleX,
  Info,
  Flame,
  Zap,
  Sparkles,
  Eye,
  Bell,
  CircleDashed,
  Monitor,
  Laptop,
  Smartphone,
  Server,
  HardDrive,
  Cpu,
  Cloud,
  Wifi,
  Network,
  Cable,
  CodeXml,
  Terminal,
  Bug,
  Wrench,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Lock,
  LockOpen,
  KeyRound,
  Fingerprint,
  ScanFace,
  EyeOff,
  FileLock,
  DatabaseBackup,
  Siren,
  Pizza,
  Sandwich,
  Croissant,
  Cookie,
  CakeSlice,
  IceCreamCone,
  Apple,
  Cherry,
  Citrus,
  Grape,
  Coffee,
  CupSoda,
  Utensils,
  Soup,
  ChefHat,
  Dog,
  Cat,
  Rabbit,
  Squirrel,
  Bird,
  Fish,
  Turtle,
  Snail,
  Worm,
  Rat,
  PawPrint,
  Shell,
  FishSymbol,
  Feather,
  Smile,
  Laugh,
  Frown,
  Meh,
  Annoyed,
  Angry,
  SmilePlus,
  ThumbsUp,
  ThumbsDown,
  Heart,
  Glasses,
  PartyPopper,
  Leaf,
  Flower,
  Flower2,
  Sprout,
  TreePine,
  Trees,
  TreeDeciduous,
  Mountain,
  Sun,
  Moon,
  Rainbow,
  Snowflake,
  Waves,
  Wind,
  Plane,
  PlaneTakeoff,
  Car,
  Bus,
  Train,
  Ship,
  Map,
  MapPin,
  Navigation,
  Compass,
  Route,
  Hotel,
  House,
  Luggage,
  Earth,
  MailOpen,
  Send,
  MessageSquare,
  MessageCircle,
  Phone,
  PhoneCall,
  Video,
  Megaphone,
  Share2,
  Paperclip,
  File,
  FileSpreadsheet,
  FileCheck,
  FileClock,
  FileSearch,
  Files,
  FolderOpen,
  Notebook,
  Book,
  BookOpen,
  Library,
  Clipboard,
  Archive,
  Lightbulb,
  Brain,
  Rocket,
  Telescope,
  Microscope,
  FlaskConical,
  Atom,
  Puzzle,
  Shapes,
  Circle,
  Triangle,
  Square,
  Diamond,
  Infinity,
};

export const VIEW_ICON_NAMES = Object.keys(VIEW_ICON_LIBRARY);

// Sections rendered by the picker, in this fixed order -- deliberately NOT
// derived from VIEW_ICON_LIBRARY's insertion order, since several icons
// (Handshake, Target, Star, Flag, Database, Table2, Mail, Cloud, Eye,
// TriangleAlert, MessagesSquare, AtSign, Sparkles, FileText, Folder,
// Calendar, Bug) legitimately belong in more than one section and should
// show up in each.
export const VIEW_ICON_SECTIONS: { label: string; icons: string[] }[] = [
  { label: "Business / Standard", icons: ["Briefcase", "Building2", "Handshake", "Landmark", "Target", "Presentation", "Folder", "FileText", "ClipboardList", "Calendar", "Mail", "Globe", "Search", "Settings", "Star"] },
  { label: "Work & Productivity", icons: ["LayoutDashboard", "List", "ListChecks", "Table", "Grid3X3", "Kanban", "FolderKanban", "ClipboardCheck", "Workflow", "GitBranch", "Layers", "Milestone", "Flag", "Tag", "Inbox"] },
  { label: "Data & Analytics", icons: ["ChartBar", "ChartColumn", "ChartLine", "ChartPie", "ChartSpline", "TrendingUp", "TrendingDown", "Activity", "Gauge", "CircleGauge", "Percent", "Database", "Table2", "ArrowUpDown", "Scale"] },
  { label: "Time & Scheduling", icons: ["Clock", "Timer", "Hourglass", "Calendar", "CalendarDays", "CalendarRange", "CalendarClock", "CalendarCheck", "CalendarPlus", "AlarmClock", "History", "RefreshCw", "Play", "Pause", "TimerReset"] },
  { label: "People & Teams", icons: ["User", "Users", "UserRound", "UsersRound", "UserCheck", "UserPlus", "UserMinus", "UserCog", "UserSearch", "Contact", "IdCard", "CircleUserRound", "Handshake", "MessagesSquare", "AtSign"] },
  { label: "Status & Priority", icons: ["CircleCheck", "CheckCheck", "CircleAlert", "TriangleAlert", "CircleX", "Info", "Flag", "Flame", "Zap", "Star", "Sparkles", "Target", "Eye", "Bell", "CircleDashed"] },
  { label: "Technology", icons: ["Monitor", "Laptop", "Smartphone", "Server", "Database", "HardDrive", "Cpu", "Cloud", "Wifi", "Network", "Cable", "CodeXml", "Terminal", "Bug", "Wrench"] },
  { label: "Security", icons: ["Shield", "ShieldCheck", "ShieldAlert", "ShieldX", "Lock", "LockOpen", "KeyRound", "Fingerprint", "ScanFace", "Eye", "EyeOff", "FileLock", "DatabaseBackup", "Siren", "TriangleAlert"] },
  { label: "Food & Drinks", icons: ["Pizza", "Sandwich", "Croissant", "Cookie", "CakeSlice", "IceCreamCone", "Apple", "Cherry", "Citrus", "Grape", "Coffee", "CupSoda", "Utensils", "Soup", "ChefHat"] },
  { label: "Animals", icons: ["Dog", "Cat", "Rabbit", "Squirrel", "Bird", "Fish", "Turtle", "Snail", "Bug", "Worm", "Rat", "PawPrint", "Shell", "FishSymbol", "Feather"] },
  { label: "Faces & Reactions", icons: ["Smile", "Laugh", "Frown", "Meh", "Annoyed", "Angry", "SmilePlus", "ThumbsUp", "ThumbsDown", "Heart", "Eye", "Glasses", "Sparkles", "PartyPopper", "Flame"] },
  { label: "Nature", icons: ["Leaf", "Flower", "Flower2", "Sprout", "TreePine", "Trees", "TreeDeciduous", "Mountain", "Cloud", "Sun", "Moon", "Rainbow", "Snowflake", "Waves", "Wind"] },
  { label: "Travel & Places", icons: ["Plane", "PlaneTakeoff", "Car", "Bus", "Train", "Ship", "Map", "MapPin", "Navigation", "Compass", "Route", "Hotel", "House", "Luggage", "Earth"] },
  { label: "Communication", icons: ["Mail", "MailOpen", "Send", "Inbox", "MessageSquare", "MessageCircle", "MessagesSquare", "Phone", "PhoneCall", "Video", "AtSign", "Bell", "Megaphone", "Share2", "Paperclip"] },
  { label: "Documents & Knowledge", icons: ["File", "FileText", "FileSpreadsheet", "FileCheck", "FileClock", "FileSearch", "Files", "Folder", "FolderOpen", "Notebook", "Book", "BookOpen", "Library", "Clipboard", "Archive"] },
  { label: "Miscellaneous", icons: ["Lightbulb", "Brain", "Sparkles", "Rocket", "Telescope", "Microscope", "FlaskConical", "Atom", "Puzzle", "Shapes", "Circle", "Triangle", "Square", "Diamond", "Infinity"] },
];
